Repository breno174/petconnect-mobile, pull requests merged in 2025-04, with the labels that each got.

#45 criação layout cadastro pet #7
  petconnect/package.json
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/(drawer)/home/registerpet.tsx
  petconnect/src/app/auth/login.tsx
  petconnect/yarn.lock
Labels: Screen

#46 feat: Lista Pets (#16)
  petconnect/package.json
  petconnect/src/api/get-pet-image.ts
  petconnect/src/api/get-pets.ts
  petconnect/src/app/(drawer)/homeScreen.tsx
  petconnect/src/components/FilterBottomSheet.tsx
  petconnect/src/components/FilterOptions.tsx
  petconnect/src/components/HomeCardList.tsx
  petconnect/src/components/PetImage.tsx
  petconnect/src/interfaces/filterInterface.ts
  petconnect/src/interfaces/petInterface.ts
  petconnect/yarn.lock
Labels: Funcionalidade

#48 criação funcionalidade pet #17
  petconnect/package.json
  petconnect/src/app/(drawer)/home/registerpet.tsx
  petconnect/src/app/auth/login.tsx
  petconnect/src/context/authUserProvider.tsx
  petconnect/yarn.lock
Labels: Funcionalidade

#50 fix: fix useEffect lopping
  petconnect/src/app/auth/login.tsx
Labels: wontfix

#51 49 criar layout filter bottom sheet
  petconnect/babel.config.js
  petconnect/package.json
  petconnect/src/app/(drawer)/homeScreen.tsx
  petconnect/src/components/FilterBottomSheet.tsx
  petconnect/src/components/FilterOptions.tsx
  petconnect/src/components/ThemedButton.tsx
  petconnect/yarn.lock
Labels: Funcionalidade

#58 feat: add funcionalidade de logout #56
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/drawer/CustomDrawerContent.tsx
  petconnect/yarn.lock
Labels: Funcionalidade

#59 layout mock chat msgs #4
  firebase ajuste.txt
  petconnect/firebaseConfig.ts
  petconnect/package-lock.json
  petconnect/package.json
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/(drawer)/home/chatscreen.tsx
  petconnect/yarn.lock
Labels: Screen
