Repository breno174/petconnect-mobile, pull requests merged in 2025-03, with the labels that each got.

#32 feat: layout perfil user data [#5]
  petconnect/app.json
  petconnect/assets/images/instrutor.jpeg
  petconnect/package.json
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/(drawer)/home/userdata.tsx
  petconnect/src/app/(tabs)/_layout.tsx
  petconnect/src/app/(tabs)/index.tsx
  petconnect/yarn.lock
Labels: Screen

#33 feat: petprofile layout [#6]
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/home/petprofile.tsx
Labels: Screen

#31 feat: criada funcionalidade cadastro #14
  petconnect/src/app/(tabs)/register.tsx
  petconnect/src/components/ThemedInput.tsx
Labels: Funcionalidade

#38 35 criar funcionalidade autenticação
  petconnect/src/api/axios.ts
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/_layout.tsx
  petconnect/src/context/authUserProvider.tsx
  petconnect/src/interfaces/userInterface.ts
  petconnect/src/interfaces/userRegisterInterface.ts
  petconnect/src/services/tokenService.ts
Labels: Funcionalidade

#43 fix: fix structure
  petconnect/src/app/(drawer)/account/forgotstep.tsx
  petconnect/src/app/(drawer)/account/login.tsx
  petconnect/src/app/(drawer)/account/register.tsx
  petconnect/src/app/(drawer)/home/petprofile.tsx
  petconnect/src/app/auth/forgotpassword.tsx
  petconnect/src/app/auth/forgotstep.tsx
  petconnect/src/app/auth/login.tsx
  petconnect/yarn.lock
Labels: wontfix

#44 37 criar funcionalidade user profile (#37)
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/(drawer)/home/userdata.tsx
  petconnect/src/app/_layout.tsx
  petconnect/src/app/auth/forgotpassword.tsx
  petconnect/src/app/auth/login.tsx
  petconnect/src/app/drawer/CustomDrawerContent.tsx
  petconnect/src/app/index.tsx
  petconnect/src/context/authUserProvider.tsx
Labels: Funcionalidade
