Repository breno174/petconnect-mobile, pull requests merged in 2025-05, with the labels that each got.

#62 4 criar layout menssagens
  petconnect/package-lock.json
  petconnect/src/app/(drawer)/_layout.tsx
  petconnect/src/app/(drawer)/home/chatscreen.tsx
  petconnect/src/app/(drawer)/home/chatscreenconversation.tsx
Labels: Screen

#63 19 criar funcionalidade mensagens
  petconnect/.gitignore
  petconnect/babel.config.js
  petconnect/env.d.ts
  petconnect/package-lock.json
  petconnect/package.json
  petconnect/src/api/axios.ts
  petconnect/src/app/(drawer)/home/chatscreen.tsx
  petconnect/src/app/(drawer)/home/chatscreenconversation.tsx
  petconnect/src/app/(drawer)/home/chatscreenconversation/[userId].tsx
  petconnect/src/app/_layout.tsx
  petconnect/src/app/auth/login.tsx
  petconnect/src/context/authUserProvider.tsx
  petconnect/yarn.lock
Labels: Funcionalidade

#67 Update [userId].tsx
  petconnect/src/app/(drawer)/home/chatscreenconversation/[userId].tsx
Labels: wontfix

#66 55 criar funcionalidade edit pet
  petconnect/env.d.ts
  petconnect/src/api/edit-pet.ts
  petconnect/src/app/(drawer)/home/profileActions/[petId].tsx
  petconnect/src/app/(drawer)/home/userdata.tsx
Labels: Funcionalidade
